version: 2
registries:
  npm-jfrog:
    type: npm-registry
    url: https://instructure.jfrog.io/artifactory/api/npm/internal-npm
    token: ${{secrets.JFROG_NPM_TOKEN}}

updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "10:00"
      timezone: "America/New_York"
    open-pull-requests-limit: 1
    registries:
      - npm-jfrog
    groups:
      npm-dependencies:
        patterns:
          - "*"
        update-types:
          - "major"
          - "minor"
          - "patch"
    commit-message:
      prefix: "deps"
      include: "scope"
