version: "3.8"

services:
  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    platform: linux/amd64
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - 3306:3306

  postgres:
    image: postgres:14
    platform: linux/amd64
    restart: always
    environment:
      # postgres user is postgres
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432

  adminer:
    image: adminer:latest
    platform: linux/amd64
    restart: always
    ports:
      - 8080:8080
